In [51]:
import requests
import urllib.request
import time
from bs4 import BeautifulSoup
import re
import pandas as pd

In [84]:
state_daily_url = "https://api.covid19india.org/states_daily.json"
statewise_timeline = requests.get(state_daily_url).json()

In [85]:
statewise_df = pd.DataFrame(statewise_timeline['states_daily'])
statewise_confirmed_df = statewise_df[statewise_df['status']=="Confirmed"]
statewise_confirmed_df.drop('status',axis=1,inplace=True)

E:\python\lib\site-packages\pandas\core\frame.py:4102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [54]:
statewise_confirmed_df.reset_index(inplace=True)
dates = statewise_confirmed_df['date']
statewise_confirmed_df.drop('date',axis=1,inplace=True)

In [55]:
def get_count(num):
    try:
        return int(num)
    except:
        return 0

In [56]:
for col in statewise_confirmed_df.columns:
    statewise_confirmed_df[col] = statewise_confirmed_df[col].apply(get_count)

E:\python\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [57]:
statwise_cummulative_df = statewise_confirmed_df
for i in range(1,len(statewise_confirmed_df)):
    statwise_cummulative_df.iloc[i]=statwise_cummulative_df.iloc[i]+statwise_cummulative_df.iloc[i-1]

E:\python\lib\site-packages\pandas\core\indexing.py:205: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)
E:\python\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [58]:
print(statwise_cummulative_df.tail())
statwise_cummulative_df.drop('index',axis=1,inplace=True)

    index  an    ap  ar  as   br  ch  ct  dd    dl  ...  py    rj  sk    tg  \
40   2460  22   893   1  36  170  27  36   0  2376  ...   7  1964   0   970
41   2583  29   955   1  36  223  27  36   0  2514  ...   7  2034   0   983
42   2709  33  1016   1  36  251  28  37   0  2625  ...   8  2083   0   990
43   2838  33  1097   1  36  277  36  37   0  2918  ...   8  2185   0  1001
44   2970  33  1177   1  36  346  45  37   0  3108  ...   8  2262   0  1003

      tn  tr     tt    up  ut   wb
40  1683   2  23039  1510  47  456
41  1755   2  24447  1621  48  514
42  1821   2  26282  1793  48  571
43  1885   2  27889  1873  51  611
44  1937   2  29496  1986  51  649

[5 rows x 39 columns]

In [80]:
v=requests.get('https://api.covid19india.org/data.json')
v=v.json()
data=pd.DataFrame(v['statewise'])

In [81]:
data=data[['state','statecode']]
data['statecode'] = data['statecode'].apply(str.lower)

In [82]:
data.set_index(['statecode'],inplace=True)

In [83]:
data=data.to_dict()['state']
data

{'tt': 'Total',
 'mh': 'Maharashtra',
 'gj': 'Gujarat',
 'dl': 'Delhi',
 'rj': 'Rajasthan',
 'mp': 'Madhya Pradesh',
 'tn': 'Tamil Nadu',
 'up': 'Uttar Pradesh',
 'ap': 'Andhra Pradesh',
 'tg': 'Telangana',
 'wb': 'West Bengal',
 'jk': 'Jammu and Kashmir',
 'ka': 'Karnataka',
 'kl': 'Kerala',
 'pb': 'Punjab',
 'hr': 'Haryana',
 'br': 'Bihar',
 'or': 'Odisha',
 'jh': 'Jharkhand',
 'ut': 'Uttarakhand',
 'hp': 'Himachal Pradesh',
 'ct': 'Chhattisgarh',
 'as': 'Assam',
 'ch': 'Chandigarh',
 'an': 'Andaman and Nicobar Islands',
 'la': 'Ladakh',
 'ml': 'Meghalaya',
 'py': 'Puducherry',
 'ga': 'Goa',
 'mn': 'Manipur',
 'tr': 'Tripura',
 'mz': 'Mizoram',
 'ar': 'Arunachal Pradesh',
 'nl': 'Nagaland',
 'dn': 'Dadra and Nagar Haveli',
 'dd': 'Daman and Diu',
 'ld': 'Lakshadweep',
 'sk': 'Sikkim'}

In [63]:
data['state']

{'tt': 'Total',
 'mh': 'Maharashtra',
 'gj': 'Gujarat',
 'dl': 'Delhi',
 'rj': 'Rajasthan',
 'mp': 'Madhya Pradesh',
 'tn': 'Tamil Nadu',
 'up': 'Uttar Pradesh',
 'ap': 'Andhra Pradesh',
 'tg': 'Telangana',
 'wb': 'West Bengal',
 'jk': 'Jammu and Kashmir',
 'ka': 'Karnataka',
 'kl': 'Kerala',
 'pb': 'Punjab',
 'hr': 'Haryana',
 'br': 'Bihar',
 'or': 'Odisha',
 'jh': 'Jharkhand',
 'ut': 'Uttarakhand',
 'hp': 'Himachal Pradesh',
 'ct': 'Chhattisgarh',
 'as': 'Assam',
 'ch': 'Chandigarh',
 'an': 'Andaman and Nicobar Islands',
 'la': 'Ladakh',
 'ml': 'Meghalaya',
 'py': 'Puducherry',
 'ga': 'Goa',
 'mn': 'Manipur',
 'tr': 'Tripura',
 'mz': 'Mizoram',
 'ar': 'Arunachal Pradesh',
 'nl': 'Nagaland',
 'dn': 'Dadra and Nagar Haveli',
 'dd': 'Daman and Diu',
 'ld': 'Lakshadweep',
 'sk': 'Sikkim'}

In [66]:
statwise_cummulative_df.rename(columns=data['state'],inplace=True)

In [67]:
statwise_cummulative_df

,Andaman and Nicobar Islands,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,Daman and Diu,Delhi,Dadra and Nagar Haveli,...,Puducherry,Rajasthan,Sikkim,Telangana,Tamil Nadu,Tripura,Total,Uttar Pradesh,Uttarakhand,West Bengal
0,0,1,0,0,0,0,0,0,7,0,...,0,3,0,1,1,0,81,12,0,0
1,0,1,0,0,0,0,0,0,7,0,...,0,4,0,3,1,0,108,13,0,0
2,0,1,0,0,0,0,0,0,7,0,...,1,4,0,4,1,0,123,13,1,0
3,0,1,0,0,0,0,0,0,8,0,...,1,4,0,5,1,0,134,15,1,1
4,0,1,0,0,0,0,0,0,10,0,...,1,7,0,13,2,0,171,17,2,1
5,0,3,0,0,0,1,1,0,14,0,...,1,9,0,16,3,0,198,20,3,1
6,0,3,0,0,0,5,1,0,20,0,...,1,17,0,19,3,0,256,24,3,2
7,0,5,0,0,0,5,1,0,27,0,...,1,24,0,21,6,0,334,28,3,4
8,0,6,0,0,2,6,1,0,27,0,...,1,28,0,27,9,0,401,30,3,7
9,0,7,0,0,3,7,1,0,30,0,...,1,32,0,33,12,0,503,32,4,7
10,0,8,0,0,3,7,1,0,30,0,...,1,32,0,37,18,0,567,35,4,9
11,0,10,0,0,4,7,3,0,35,0,...,1,38,0,41,26,0,657,38,5,9
12,1,11,0,0,7,7,6,0,36,0,...,1,40,0,44,29,0,722,42,5,10
13,6,13,0,0,9,8,6,0,40,0,...,1,50,0,59,38,0,886,49,5,15
14,9,19,0,0,11,8,7,0,49,0,...,1,54,0,67,42,0,1029,65,6,18
15,9,21,0,0,15,8,7,0,72,0,...,1,59,0,70,50,0,1139,72,7,21
16,10,23,0,0,15,13,8,0,97,0,...,1,79,0,77,67,0,1326,96,7,22
17,10,44,0,1,21,15,9,0,120,0,...,1,93,0,97,124,0,1635,104,7,37
18,10,111,0,16,24,17,9,0,152,0,...,3,120,0,127,234,0,2059,117,7,37
19,10,149,1,16,29,18,9,0,293,0,...,5,133,0,154,309,0,2545,128,10,53
20,10,164,1,23,31,18,9,0,386,0,...,5,179,0,229,411,0,3105,174,16,53
21,10,192,1,26,32,18,10,0,445,0,...,5,206,0,272,485,0,3684,234,22,53
22,10,256,1,26,32,18,10,0,503,0,...,5,266,0,334,571,0,4293,278,26,80
23,10,303,1,26,32,18,10,0,525,0,...,5,301,0,364,621,1,4777,305,31,80
24,10,314,1,28,38,18,10,0,576,0,...,5,343,0,404,690,1,5349,332,31,91
25,11,348,1,28,39,18,10,0,669,0,...,5,383,0,453,738,1,5914,361,35,99
26,11,363,1,29,58,18,18,0,720,0,...,5,463,0,471,834,1,6727,410,35,103
27,11,381,1,29,60,19,18,0,903,0,...,7,561,0,487,911,2,7598,433,35,116
28,11,405,1,29,64,19,25,0,1069,0,...,7,700,0,503,969,2,8452,452,35,126
29,11,420,1,30,64,21,31,0,1154,0,...,7,804,0,531,1075,2,9210,483,35,134
30,11,439,1,32,66,21,31,0,1510,0,...,7,897,0,592,1173,2,10453,558,35,152
31,11,484,1,33,66,21,33,0,1561,0,...,7,1005,0,644,1204,2,11484,660,37,190
32,11,525,1,33,72,21,33,0,1578,0,...,7,1076,0,650,1242,2,12370,735,37,213
33,11,534,1,35,83,21,36,0,1640,0,...,7,1131,0,700,1267,2,13431,805,37,231
34,12,572,1,35,85,21,36,0,1707,0,...,7,1229,0,766,1323,2,14353,849,40,255
35,14,603,1,35,86,23,36,0,1893,0,...,7,1351,0,809,1372,2,15724,975,42,287
36,15,647,1,35,96,26,36,0,2003,0,...,7,1478,0,858,1477,2,17304,1100,44,310
37,16,722,1,35,113,26,36,0,2081,0,...,7,1576,0,872,1520,2,18543,1184,46,339
38,17,757,1,35,126,27,36,0,2156,0,...,7,1735,0,928,1596,2,20080,1337,46,392
39,18,813,1,35,143,27,36,0,2248,0,...,7,1888,0,943,1629,2,21372,1449,46,423
40,22,893,1,36,170,27,36,0,2376,0,...,7,1964,0,970,1683,2,23039,1510,47,456
41,29,955,1,36,223,27,36,0,2514,0,...,7,2034,0,983,1755,2,24447,1621,48,514
42,33,1016,1,36,251,28,37,0,2625,0,...,8,2083,0,990,1821,2,26282,1793,48,571
43,33,1097,1,36,277,36,37,0,2918,0,...,8,2185,0,1001,1885,2,27889,1873,51,611
44,33,1177,1,36,346,45,37,0,3108,0,...,8,2262,0,1003,1937,2,29496,1986,51,649

In [70]:
statwise_cummulative_df['date'] = dates

E:\python\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [71]:
statwise_cummulative_df

,Andaman and Nicobar Islands,Andhra Pradesh,Arunachal Pradesh,Assam,Bihar,Chandigarh,Chhattisgarh,Daman and Diu,Delhi,Dadra and Nagar Haveli,...,Rajasthan,Sikkim,Telangana,Tamil Nadu,Tripura,Total,Uttar Pradesh,Uttarakhand,West Bengal,date
0,0,1,0,0,0,0,0,0,7,0,...,3,0,1,1,0,81,12,0,0,14-Mar-20
1,0,1,0,0,0,0,0,0,7,0,...,4,0,3,1,0,108,13,0,0,15-Mar-20
2,0,1,0,0,0,0,0,0,7,0,...,4,0,4,1,0,123,13,1,0,16-Mar-20
3,0,1,0,0,0,0,0,0,8,0,...,4,0,5,1,0,134,15,1,1,17-Mar-20
4,0,1,0,0,0,0,0,0,10,0,...,7,0,13,2,0,171,17,2,1,18-Mar-20
5,0,3,0,0,0,1,1,0,14,0,...,9,0,16,3,0,198,20,3,1,19-Mar-20
6,0,3,0,0,0,5,1,0,20,0,...,17,0,19,3,0,256,24,3,2,20-Mar-20
7,0,5,0,0,0,5,1,0,27,0,...,24,0,21,6,0,334,28,3,4,21-Mar-20
8,0,6,0,0,2,6,1,0,27,0,...,28,0,27,9,0,401,30,3,7,22-Mar-20
9,0,7,0,0,3,7,1,0,30,0,...,32,0,33,12,0,503,32,4,7,23-Mar-20
10,0,8,0,0,3,7,1,0,30,0,...,32,0,37,18,0,567,35,4,9,24-Mar-20
11,0,10,0,0,4,7,3,0,35,0,...,38,0,41,26,0,657,38,5,9,25-Mar-20
12,1,11,0,0,7,7,6,0,36,0,...,40,0,44,29,0,722,42,5,10,26-Mar-20
13,6,13,0,0,9,8,6,0,40,0,...,50,0,59,38,0,886,49,5,15,27-Mar-20
14,9,19,0,0,11,8,7,0,49,0,...,54,0,67,42,0,1029,65,6,18,28-Mar-20
15,9,21,0,0,15,8,7,0,72,0,...,59,0,70,50,0,1139,72,7,21,29-Mar-20
16,10,23,0,0,15,13,8,0,97,0,...,79,0,77,67,0,1326,96,7,22,30-Mar-20
17,10,44,0,1,21,15,9,0,120,0,...,93,0,97,124,0,1635,104,7,37,31-Mar-20
18,10,111,0,16,24,17,9,0,152,0,...,120,0,127,234,0,2059,117,7,37,01-Apr-20
19,10,149,1,16,29,18,9,0,293,0,...,133,0,154,309,0,2545,128,10,53,02-Apr-20
20,10,164,1,23,31,18,9,0,386,0,...,179,0,229,411,0,3105,174,16,53,03-Apr-20
21,10,192,1,26,32,18,10,0,445,0,...,206,0,272,485,0,3684,234,22,53,04-Apr-20
22,10,256,1,26,32,18,10,0,503,0,...,266,0,334,571,0,4293,278,26,80,05-Apr-20
23,10,303,1,26,32,18,10,0,525,0,...,301,0,364,621,1,4777,305,31,80,06-Apr-20
24,10,314,1,28,38,18,10,0,576,0,...,343,0,404,690,1,5349,332,31,91,07-Apr-20
25,11,348,1,28,39,18,10,0,669,0,...,383,0,453,738,1,5914,361,35,99,08-Apr-20
26,11,363,1,29,58,18,18,0,720,0,...,463,0,471,834,1,6727,410,35,103,09-Apr-20
27,11,381,1,29,60,19,18,0,903,0,...,561,0,487,911,2,7598,433,35,116,10-Apr-20
28,11,405,1,29,64,19,25,0,1069,0,...,700,0,503,969,2,8452,452,35,126,11-Apr-20
29,11,420,1,30,64,21,31,0,1154,0,...,804,0,531,1075,2,9210,483,35,134,12-Apr-20
30,11,439,1,32,66,21,31,0,1510,0,...,897,0,592,1173,2,10453,558,35,152,13-Apr-20
31,11,484,1,33,66,21,33,0,1561,0,...,1005,0,644,1204,2,11484,660,37,190,14-Apr-20
32,11,525,1,33,72,21,33,0,1578,0,...,1076,0,650,1242,2,12370,735,37,213,15-Apr-20
33,11,534,1,35,83,21,36,0,1640,0,...,1131,0,700,1267,2,13431,805,37,231,16-Apr-20
34,12,572,1,35,85,21,36,0,1707,0,...,1229,0,766,1323,2,14353,849,40,255,17-Apr-20
35,14,603,1,35,86,23,36,0,1893,0,...,1351,0,809,1372,2,15724,975,42,287,18-Apr-20
36,15,647,1,35,96,26,36,0,2003,0,...,1478,0,858,1477,2,17304,1100,44,310,19-Apr-20
37,16,722,1,35,113,26,36,0,2081,0,...,1576,0,872,1520,2,18543,1184,46,339,20-Apr-20
38,17,757,1,35,126,27,36,0,2156,0,...,1735,0,928,1596,2,20080,1337,46,392,21-Apr-20
39,18,813,1,35,143,27,36,0,2248,0,...,1888,0,943,1629,2,21372,1449,46,423,22-Apr-20
40,22,893,1,36,170,27,36,0,2376,0,...,1964,0,970,1683,2,23039,1510,47,456,23-Apr-20
41,29,955,1,36,223,27,36,0,2514,0,...,2034,0,983,1755,2,24447,1621,48,514,24-Apr-20
42,33,1016,1,36,251,28,37,0,2625,0,...,2083,0,990,1821,2,26282,1793,48,571,25-Apr-20
43,33,1097,1,36,277,36,37,0,2918,0,...,2185,0,1001,1885,2,27889,1873,51,611,26-Apr-20
44,33,1177,1,36,346,45,37,0,3108,0,...,2262,0,1003,1937,2,29496,1986,51,649,27-Apr-20

In [72]:
data = {}
for col in statwise_cummulative_df.columns:
    data[col]=statwise_cummulative_df[col].tolist()

In [73]:
data

{'Andaman and Nicobar Islands': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  6,
  9,
  9,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  10,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  11,
  12,
  14,
  15,
  16,
  17,
  18,
  22,
  29,
  33,
  33,
  33],
 'Andhra Pradesh': [1,
  1,
  1,
  1,
  1,
  3,
  3,
  5,
  6,
  7,
  8,
  10,
  11,
  13,
  19,
  21,
  23,
  44,
  111,
  149,
  164,
  192,
  256,
  303,
  314,
  348,
  363,
  381,
  405,
  420,
  439,
  484,
  525,
  534,
  572,
  603,
  647,
  722,
  757,
  813,
  893,
  955,
  1016,
  1097,
  1177],
 'Arunachal Pradesh': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 'Assam': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  16,
  16,
  23,
  26,
  26,
  26,
  28,
  28,
  29,
  29,
  29,
  30,
  32,
  33,
  33,
  35,
  35,
  35,
  35,
  35,
  35,
  35,
  36,
  36,
  36,
  36,
  36],
 'Bihar': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  3,
  3,
  4,
  7,
  9,
  11,
  15,
  15,
  21,
  24,
  29,
  31,
  32,
  32,
  32,
  38,
  39,
  58,
  60,
  64,
  64,
  66,
  66,
  72,
  83,
  85,
  86,
  96,
  113,
  126,
  143,
  170,
  223,
  251,
  277,
  346],
 'Chandigarh': [0,
  0,
  0,
  0,
  0,
  1,
  5,
  5,
  6,
  7,
  7,
  7,
  7,
  8,
  8,
  8,
  13,
  15,
  17,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  19,
  19,
  21,
  21,
  21,
  21,
  21,
  21,
  23,
  26,
  26,
  27,
  27,
  27,
  27,
  28,
  36,
  45],
 'Chhattisgarh': [0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  3,
  6,
  6,
  7,
  7,
  8,
  9,
  9,
  9,
  9,
  10,
  10,
  10,
  10,
  10,
  18,
  18,
  25,
  31,
  31,
  33,
  33,
  36,
  36,
  36,
  36,
  36,
  36,
  36,
  36,
  36,
  37,
  37,
  37],
 'Daman and Diu': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'Delhi': [7,
  7,
  7,
  8,
  10,
  14,
  20,
  27,
  27,
  30,
  30,
  35,
  36,
  40,
  49,
  72,
  97,
  120,
  152,
  293,
  386,
  445,
  503,
  525,
  576,
  669,
  720,
  903,
  1069,
  1154,
  1510,
  1561,
  1578,
  1640,
  1707,
  1893,
  2003,
  2081,
  2156,
  2248,
  2376,
  2514,
  2625,
  2918,
  3108],
 'Dadra and Nagar Haveli': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'Goa': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  3,
  3,
  3,
  3,
  5,
  5,
  5,
  5,
  5,
  6,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7],
 'Gujarat': [0,
  0,
  0,
  0,
  0,
  2,
  7,
  14,
  18,
  30,
  34,
  38,
  43,
  47,
  55,
  63,
  70,
  74,
  87,
  88,
  95,
  108,
  128,
  146,
  175,
  186,
  262,
  378,
  468,
  516,
  572,
  650,
  766,
  929,
  1099,
  1376,
  1743,
  1939,
  2178,
  2407,
  2624,
  2815,
  3071,
  3301,
  3548],
 'Himachal Pradesh': [0,
  0,
  0,
  0,
  0,
  0,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  3,
  6,
  6,
  13,
  14,
  18,
  27,
  27,
  28,
  28,
  32,
  32,
  32,
  33,
  35,
  35,
  38,
  39,
  39,
  39,
  39,
  39,
  40,
  40,
  40,
  40,
  40],
 'Haryana': [14,
  14,
  14,
  15,
  16,
  17,
  19,
  21,
  21,
  28,
  30,
  31,
  32,
  33,
  35,
  35,
  36,
  43,
  43,
  49,
  58,
  84,
  90,
  110,
  143,
  167,
  170,
  176,
  179,
  195,
  196,
  198,
  204,
  215,
  223,
  232,
  250,
  251,
  255,
  264,
  270,
  275,
  287,
  296,
  301],
 'Jharkhand': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  2,
  2,
  2,
  3,
  4,
  4,
  4,
  13,
  14,
  17,
  19,
  24,
  27,
  28,
  29,
  32,
  33,
  41,
  46,
  46,
  46,
  53,
  59,
  67,
  82,
  103],
 'Jammu and Kashmir': [2,
  2,
  3,
  3,
  4,
  4,
  4,
  4,
  4,
  4,
  6,
  11,
  14,
  20,
  33,
  38,
  49,
  55,
  62,
  70,
  75,
  92,
  106,
  109,
  125,
  158,
  184,
  207,
  224,
  245,
  270,
  278,
  300,
  314,
  328,
  341,
  354,
  368,
  380,
  407,
  434,
  454,
  494,
  523,
  546],
 'Karnataka': [6,
  6,
  7,
  9,
  14,
  15,
  15,
  20,
  26,
  33,
  41,
  51,
  55,
  64,
  81,
  83,
  88,
  101,
  110,
  124,
  128,
  144,
  151,
  163,
  175,
  181,
  197,
  207,
  215,
  232,
  247,
  260,
  279,
  315,
  359,
  384,
  390,
  408,
  418,
  427,
  445,
  474,
  500,
  503,
  512],
 'Kerala': [19,
  24,
  27,
  27,
  27,
  28,
  40,
  52,
  67,
  95,
  109,
  118,
  137,
  176,
  182,
  202,
  234,
  241,
  265,
  286,
  295,
  306,
  314,
  327,
  335,
  344,
  356,
  363,
  373,
  375,
  378,
  386,
  387,
  394,
  395,
  399,
  401,
  407,
  426,
  437,
  447,
  450,
  457,
  468,
  481],
 'Ladakh': [0,
  0,
  0,
  0,
  8,
  8,
  10,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  13,
  14,
  14,
  14,
  14,
  14,
  14,
  14,
  15,
  15,
  15,
  17,
  17,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  18,
  20,
  20,
  20],
 'Lakshadweep': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'Maharashtra': [14,
  32,
  38,
  41,
  44,
  48,
  52,
  64,
  74,
  97,
  107,
  122,
  125,
  156,
  186,
  203,
  220,
  302,
  335,
  423,
  487,
  635,
  747,
  868,
  1018,
  1135,
  1364,
  1574,
  1761,
  1982,
  2334,
  2680,
  2916,
  3201,
  3321,
  3648,
  4200,
  4666,
  5218,
  5649,
  6427,
  6817,
  7628,
  8068,
  8590],
 'Meghalaya': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  7,
  9,
  9,
  11,
  11,
  11,
  12,
  12,
  12,
  12,
  12,
  12,
  12],
 'Manipur': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2],
 'Madhya Pradesh': [0,
  0,
  0,
  0,
  0,
  0,
  4,
  4,
  6,
  6,
  7,
  15,
  20,
  29,
  39,
  39,
  47,
  66,
  98,
  107,
  154,
  179,
  193,
  256,
  290,
  341,
  411,
  451,
  529,
  562,
  614,
  741,
  938,
  1164,
  1310,
  1402,
  1407,
  1485,
  1552,
  1587,
  1687,
  1846,
  1945,
  2090,
  2165],
 'Mizoram': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 'Nagaland': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'Odisha': [0,
  0,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  3,
  3,
  3,
  3,
  3,
  4,
  5,
  5,
  20,
  21,
  39,
  40,
  42,
  42,
  48,
  50,
  54,
  54,
  55,
  60,
  60,
  60,
  60,
  61,
  61,
  74,
  79,
  83,
  89,
  94,
  100,
  103,
  118],
 'Punjab': [1,
  1,
  1,
  1,
  2,
  2,
  3,
  13,
  21,
  23,
  29,
  31,
  33,
  38,
  38,
  38,
  41,
  42,
  46,
  47,
  53,
  65,
  68,
  79,
  99,
  106,
  130,
  151,
  158,
  170,
  176,
  184,
  186,
  197,
  211,
  234,
  244,
  245,
  251,
  278,
  283,
  298,
  308,
  322,
  330],
 'Puducherry': [0,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  3,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  5,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  7,
  8,
  8,
  8],
 'Rajasthan': [3,
  4,
  4,
  4,
  7,
  9,
  17,
  24,
  28,
  32,
  32,
  38,
  40,
  50,
  54,
  59,
  79,
  93,
  120,
  133,
  179,
  206,
  266,
  301,
  343,
  383,
  463,
  561,
  700,
  804,
  897,
  1005,
  1076,
  1131,
  1229,
  1351,
  1478,
  1576,
  1735,
  1888,
  1964,
  2034,
  2083,
  2185,
  2262],
 'Sikkim': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'Telangana': [1,
  3,
  4,
  5,
  13,
  16,
  19,
  21,
  27,
  33,
  37,
  41,
  44,
  59,
  67,
  70,
  77,
  97,
  127,
  154,
  229,
  272,
  334,
  364,
  404,
  453,
  471,
  487,
  503,
  531,
  592,
  644,
  650,
  700,
  766,
  809,
  858,
  872,
  928,
  943,
  970,
  983,
  990,
  1001,
  1003],
 'Tamil Nadu': [1,
  1,
  1,
  1,
  2,
  3,
  3,
  6,
  9,
  12,
  18,
  26,
  29,
  38,
  42,
  50,
  67,
  124,
  234,
  309,
  411,
  485,
  571,
  621,
  690,
  738,
  834,
  911,
  969,
  1075,
  1173,
  1204,
  1242,
  1267,
  1323,
  1372,
  1477,
  1520,
  1596,
  1629,
  1683,
  1755,
  1821,
  1885,
  1937],
 'Tripura': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2],
 'Total': [81,
  108,
  123,
  134,
  171,
  198,
  256,
  334,
  401,
  503,
  567,
  657,
  722,
  886,
  1029,
  1139,
  1326,
  1635,
  2059,
  2545,
  3105,
  3684,
  4293,
  4777,
  5349,
  5914,
  6727,
  7598,
  8452,
  9210,
  10453,
  11484,
  12370,
  13431,
  14353,
  15724,
  17304,
  18543,
  20080,
  21372,
  23039,
  24447,
  26282,
  27889,
  29496],
 'Uttar Pradesh': [12,
  13,
  13,
  15,
  17,
  20,
  24,
  28,
  30,
  32,
  35,
  38,
  42,
  49,
  65,
  72,
  96,
  104,
  117,
  128,
  174,
  234,
  278,
  305,
  332,
  361,
  410,
  433,
  452,
  483,
  558,
  660,
  735,
  805,
  849,
  975,
  1100,
  1184,
  1337,
  1449,
  1510,
  1621,
  1793,
  1873,
  1986],
 'Uttarakhand': [0,
  0,
  1,
  1,
  2,
  3,
  3,
  3,
  3,
  4,
  4,
  5,
  5,
  5,
  6,
  7,
  7,
  7,
  7,
  10,
  16,
  22,
  26,
  31,
  31,
  35,
  35,
  35,
  35,
  35,
  35,
  37,
  37,
  37,
  40,
  42,
  44,
  46,
  46,
  46,
  47,
  48,
  48,
  51,
  51],
 'West Bengal': [0,
  0,
  0,
  1,
  1,
  1,
  2,
  4,
  7,
  7,
  9,
  9,
  10,
  15,
  18,
  21,
  22,
  37,
  37,
  53,
  53,
  53,
  80,
  80,
  91,
  99,
  103,
  116,
  126,
  134,
  152,
  190,
  213,
  231,
  255,
  287,
  310,
  339,
  392,
  423,
  456,
  514,
  571,
  611,
  649],
 'date': ['14-Mar-20',
  '15-Mar-20',
  '16-Mar-20',
  '17-Mar-20',
  '18-Mar-20',
  '19-Mar-20',
  '20-Mar-20',
  '21-Mar-20',
  '22-Mar-20',
  '23-Mar-20',
  '24-Mar-20',
  '25-Mar-20',
  '26-Mar-20',
  '27-Mar-20',
  '28-Mar-20',
  '29-Mar-20',
  '30-Mar-20',
  '31-Mar-20',
  '01-Apr-20',
  '02-Apr-20',
  '03-Apr-20',
  '04-Apr-20',
  '05-Apr-20',
  '06-Apr-20',
  '07-Apr-20',
  '08-Apr-20',
  '09-Apr-20',
  '10-Apr-20',
  '11-Apr-20',
  '12-Apr-20',
  '13-Apr-20',
  '14-Apr-20',
  '15-Apr-20',
  '16-Apr-20',
  '17-Apr-20',
  '18-Apr-20',
  '19-Apr-20',
  '20-Apr-20',
  '21-Apr-20',
  '22-Apr-20',
  '23-Apr-20',
  '24-Apr-20',
  '25-Apr-20',
  '26-Apr-20',
  '27-Apr-20']}